In [4]:
import numpy as np

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.exp(arrm)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
x = np.random.randn(8)
y = np.random.randn(8)

print(x)
print(y)

np.maximum(x, y)

[-1.87432663 -1.09835622 -0.16771382 -0.72748947 -1.23619191  0.03668366
 -0.37083276 -0.02817904]
[-2.1245908  -0.66003297 -0.73591051  0.15080941  2.11012543  1.25503283
  0.95771334 -0.49798358]


array([-1.87432663, -0.66003297, -0.16771382,  0.15080941,  2.11012543,
        1.25503283,  0.95771334, -0.02817904])

In [10]:
arr = np.random.randn(7) * 5
arr

array([  5.07198862,   3.84376188,  -3.36272941,   0.77463639,
       -11.22684524,  -5.53328272,   2.09128024])

In [13]:
raminder, whole_part = np.modf(arr)
print(raminder)
print(whole_part)

[ 0.07198862  0.84376188 -0.36272941  0.77463639 -0.22684524 -0.53328272
  0.09128024]
[  5.   3.  -3.   0. -11.  -5.   2.]


In [15]:
np.sqrt(arr)

<ipython-input-15-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([2.2521076 , 1.96055142,        nan, 0.8801343 ,        nan,
              nan, 1.44612594])

In [17]:
np.sqrt(arr, arr)

<ipython-input-17-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([2.2521076 , 1.96055142,        nan, 0.8801343 ,        nan,
              nan, 1.44612594])

In [18]:
arr

array([2.2521076 , 1.96055142,        nan, 0.8801343 ,        nan,
              nan, 1.44612594])