In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr = np.random.randn(6, 3)
arr

array([[ 1.5443403 ,  1.5629485 , -0.25426845],
       [-0.16872424, -0.42443185,  0.71184778],
       [-0.14731258,  1.09788694,  0.4939166 ],
       [-0.08475422,  0.76609578, -0.35950416],
       [-1.05698374,  0.45962829,  0.72862221],
       [-0.48461469, -1.23373796,  1.0619447 ]])

In [7]:
np.dot(arr.T, arr)

array([[ 3.79440514,  2.3707418 , -1.83984946],
       [ 2.3707418 ,  6.1485764 , -1.4079555 ],
       [-1.83984946, -1.4079555 ,  2.60319341]])

In [11]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [13]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [14]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])