In [7]:
import numpy as np
from numpy.linalg import inv, qr

In [8]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23], [-1, 7], [8, 9]])

print(x)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [9]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [11]:
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 1.65615072, -0.76358309,  2.94144756, -0.95891429, -0.44254799],
       [-0.76358309,  0.87201911, -1.64937843,  0.51036671,  0.27296057],
       [ 2.94144756, -1.64937843,  5.85857065, -1.87333302, -0.92328993],
       [-0.95891429,  0.51036671, -1.87333302,  1.21801101,  0.86867469],
       [-0.44254799,  0.27296057, -0.92328993,  0.86867469,  0.8353259 ]])

In [12]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.88433736e-16, -2.74618968e-15,
        -1.66552342e-16, -1.95437988e-16],
       [ 4.02453696e-16,  1.00000000e+00,  1.24710549e-15,
        -5.12542811e-16, -1.01377838e-16],
       [-5.02271026e-16, -2.57071970e-16,  1.00000000e+00,
         5.33992339e-16,  7.94957376e-16],
       [-7.76827864e-17,  1.30121014e-16,  2.76000472e-16,
         1.00000000e+00,  5.30841359e-16],
       [-1.10678301e-16,  3.10389569e-16, -6.76790757e-16,
         9.94373143e-16,  1.00000000e+00]])

In [16]:
q, r = qr(mat)
r

array([[-7.24642029,  1.49394216,  3.58331592, -3.37300719,  3.35986617],
       [ 0.        , -2.65166495, -1.40261137, -3.52117834,  3.22028172],
       [ 0.        ,  0.        , -1.53802281, -8.41214703,  7.60846949],
       [ 0.        ,  0.        ,  0.        , -1.45416668,  2.3022102 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.6231545 ]])