In [1]:
import numpy as np

arr = np.random.randn(5, 4)
arr

array([[ 0.61328253,  0.15421179,  0.858654  , -2.66854663],
       [-1.49902705, -1.79971811,  0.85266328,  0.0309646 ],
       [-0.06855827, -0.21814334, -1.40700005, -0.89040172],
       [-0.22852483,  0.74591728, -0.48412953, -0.25564235],
       [ 0.23868147, -0.72850821, -0.99018784, -0.96420639]])

In [4]:
# calculo das medias pelas colunas
print(arr.mean())
print(arr.mean(axis=1))

-0.43541096830102644
[-0.26059958 -0.60377932 -0.64602584 -0.05559486 -0.61105524]


In [5]:
#calculo das somas pelas linhas
print(arr.sum())
print(arr.sum(axis=0))

-8.70821936602053
[-0.94414616 -1.84624058 -1.17000014 -4.74783249]


In [8]:
#cumsum e cumprod não fazem agregações
arr2 = np.array([2, 4, 3, 7, 9])
arr2.cumsum()

array([ 2,  6,  9, 16, 25])

In [10]:
arr3 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr3.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [14]:
arr3.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])