In [14]:
import numpy as np

arr = np.random.randn(6)
arr

array([-0.1159986 ,  1.2743659 , -0.09810975, -1.78788818, -0.79193469,
       -1.28746753])

In [15]:
arr.sort()
arr

array([-1.78788818, -1.28746753, -0.79193469, -0.1159986 , -0.09810975,
        1.2743659 ])

In [16]:
arr2 = np.random.randn(5, 3)
arr2

array([[ 1.08470427, -1.36374   , -0.46270233],
       [-1.76230825, -1.98283685,  0.52788317],
       [ 0.13576485, -0.94994511,  0.79084586],
       [ 0.54020952,  0.69943089, -1.04159374],
       [ 0.68334442,  0.49153343,  1.06193386]])

In [17]:
arr2.sort(1)
arr2

array([[-1.36374   , -0.46270233,  1.08470427],
       [-1.98283685, -1.76230825,  0.52788317],
       [-0.94994511,  0.13576485,  0.79084586],
       [-1.04159374,  0.54020952,  0.69943089],
       [ 0.49153343,  0.68334442,  1.06193386]])