In [1]:
import numpy as np

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])


In [2]:
#List comprehension em python interpretado
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [3]:
#Uso de np.where
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [4]:
arr = np.random.randn(4, 4)
arr

array([[-0.00782746, -3.07007707, -0.9518903 ,  0.04006201],
       [-1.43973379, -0.8104653 ,  1.00626461,  0.60301931],
       [-0.23391283, -0.2229301 , -1.7908553 , -0.28142076],
       [-1.42600003,  0.85719537, -0.42290488, -1.34810132]])

In [5]:
arr > 0

array([[False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [6]:
np.where(arr > 0, 1, -1)

array([[-1, -1, -1,  1],
       [-1, -1,  1,  1],
       [-1, -1, -1, -1],
       [-1,  1, -1, -1]])

In [7]:
np.where(arr > 0, 1, arr)

array([[-0.00782746, -3.07007707, -0.9518903 ,  1.        ],
       [-1.43973379, -0.8104653 ,  1.        ,  1.        ],
       [-0.23391283, -0.2229301 , -1.7908553 , -0.28142076],
       [-1.42600003,  1.        , -0.42290488, -1.34810132]])