In [6]:
import numpy as np

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

[6.  7.5 8.  0.  1. ]
1
(5,)
float64


In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7 , 8]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32


In [22]:
arr0 = np.zeros(10)
print(arr0)

arrzeros1 = np.zeros((3, 4))
print(arrzeros1)

arr_empyt = np.empty((5, 8))
print(arr_empyt)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10.]]


In [23]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
arr3 = np.array([3.7, -1.2, -6.2, 8, 0.5, 3.25, 10.1])
arr3 = arr3.astype(np.int32)
print(arr3)
print(arr2.dtype)

arr4 = np.array(['2.15', '8.20', '9.015'])
arr4 = arr4.astype(np.float64)
print(arr4)
print(arr4.dtype)

arr3.astype(arr4.dtype)

[ 3 -1 -6  8  0  3 10]
int32
[2.15  8.2   9.015]
float64


array([ 3., -1., -6.,  8.,  0.,  3., 10.])