In [7]:
import numpy as np

data = np.random.randn(2, 3)
print(data)
print(data * 10)
print(data + data)

[[ 1.67708688  0.80579457 -1.5401847 ]
 [-1.92588372 -1.48026463 -1.48207291]]

[[ 16.77086878   8.05794566 -15.40184699]
 [-19.25883725 -14.80264629 -14.82072909]]

[[ 3.35417376  1.61158913 -3.0803694 ]
 [-3.85176745 -2.96052926 -2.96414582]]


In [9]:
print(data.shape)
print(data.dtype)

(2, 3)
float64
