In [17]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [18]:
print(data)

[[-0.36025569 -0.21082572  0.81441152 -1.40615093]
 [ 0.25564022 -1.8462204   0.33736547 -1.01890134]
 [ 0.97102276  1.57655271 -1.59386074  0.01337086]
 [ 1.60728559  0.3506375   1.07086158  1.84385424]
 [ 0.15633737 -0.61346228 -0.93733076  1.41655717]
 [-0.30050665 -0.86191981 -0.57937188 -0.30592719]
 [-0.70706472 -0.82082658  1.18816166  3.11873225]]


In [20]:
print(names == 'Bob')
print(data[names == 'Bob'])


[ True False False  True False False False]
[[-0.36025569 -0.21082572  0.81441152 -1.40615093]
 [ 1.60728559  0.3506375   1.07086158  1.84385424]]


In [22]:
print(data[names == 'Bob', 2:])
print(data[~(names == 'Bob')])

[[ 0.81441152 -1.40615093]
 [ 1.07086158  1.84385424]]
[[ 0.25564022 -1.8462204   0.33736547 -1.01890134]
 [ 0.97102276  1.57655271 -1.59386074  0.01337086]
 [ 0.15633737 -0.61346228 -0.93733076  1.41655717]
 [-0.30050665 -0.86191981 -0.57937188 -0.30592719]
 [-0.70706472 -0.82082658  1.18816166  3.11873225]]


In [31]:
data[data < 0] = 0
print(data)

[[7.         7.         7.         7.        ]
 [0.25564022 0.         0.33736547 0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         1.18816166 3.11873225]]


In [30]:
data[names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.25564022 0.         0.33736547 0.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         1.18816166 3.11873225]]
