In [4]:
import numpy as np

arr = np.arange(10)
print(arr)

print(arr[5:8])

arr[5:8] = 12

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [7]:
arr_slice = arr[5:8]
print(arr_slice)

arr_slice[1] = 123456

print(arr)

arr_slice[:] = 64
print(arr)



[    12 123456     12]
[     0      1      2      3      4     12 123456     12      8      9]
[ 0  1  2  3  4 64 64 64  8  9]


In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
print(arr2[2])

print(arr2[0][2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]


3

In [17]:
arr3 = np.array([[[1, 2, 3,], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

print(arr3[0])

old_values = arr3[0].copy()
arr3[0] = 42

print(arr3)

arr3[0] = old_values
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
